services:
  - type: web
    name: clouddrive-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      # You will paste your MongoDB and AWS variables securely inside Render's dashboard!
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_NAME
        sync: false
